### ISSUE TITLE
Repo name issue

### ISSUE THREAD

**Issue by ibelem** [Honry/web-test-suite#1]
If we don't test nw.js but the Chrome or other runtimes, what's the repo name should be? I thought nwjs-iot- like the test suite name in Crosswalk-Test-Suite rather than the repo name?

**Comment by Honry** [comment]
Agree, how about webqa-test-suite?

**Comment by Honry** [comment]
We have a consistent conclusion, rename the repo as ```web-test-suite```, close it.
